In this assignement, feel free to use the `sparse` module from `scipy`.

Use the cell below for your imports.

In [ ]:
import numpy as np
from scipy.sparse import coo_matrix
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import spsolve


implement the function `mat_mul_coo` that takes two sparse matrices in `coo` and returns their product.

In [16]:
import numpy as np
from scipy.sparse import coo_matrix

def mat_mul_coo(matrix1, matrix2):
    # perform matrix multiplication using COO format
    result_data = []
    result_row_indices = []
    result_col_indices = []
    for i,j in zip(matrix1.row, matrix1.col):
        row = matrix1.getrow(i)
        col = matrix2.getcol(j)
        dot_product = row.dot(col)[0, 0]
        if dot_product != 0:
            result_data.append(dot_product)
            result_row_indices.append(i)
            result_col_indices.append(j)

    # construct the resulting sparse matrix in COO format
    result = coo_matrix((result_data, (result_row_indices, result_col_indices)), shape=(matrix1.shape[0], matrix2.shape[1]))
    return result.toarray()

In [18]:
from scipy.sparse import coo_matrix

# create two sparse matrices in COO format
data1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
row1 = [0, 0, 0, 1, 1, 1, 2, 2, 2]
col1 = [0, 1, 2, 0, 1, 2, 0, 1, 2]

data2 = [1, 0, 0, 0, 1, 0, 0, 0, 1]
row2 = [0, 1, 2, 0, 1, 2, 0, 1, 2]
col2 = [0, 1, 2, 0, 1, 2, 0, 1, 2]

matrix1 = coo_matrix((data1, (row1, col1)))
matrix2 = coo_matrix((data2, (row2, col2)))

# perform matrix multiplication using COO format
result = mat_mul_coo(matrix1, matrix2)

# print the resulting sparse matrix in COO format
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


implement the function `mat_mul_csr` that takes two sparse matrices in `csr` format and returns their product.

In [20]:
import numpy as np
from scipy.sparse import csr_matrix

def mat_mul_csr(matrix1, matrix2):
    # perform matrix multiplication using CSR format
    result_data = []
    result_indices = []
    result_indptr = [0]
    for i in range(matrix1.shape[0]):
        for j in range(matrix2.shape[1]):
            dot_product = 0
            for k in range(matrix1.shape[1]):
                dot_product += matrix1[i,k] * matrix2[k,j]
            if dot_product != 0:
                result_data.append(dot_product)
                result_indices.append(j)
        result_indptr.append(len(result_data))

    # construct the resulting sparse matrix in CSR format
    result = csr_matrix((result_data, result_indices, result_indptr), shape=(matrix1.shape[0], matrix2.shape[1]))
    return result.toarray()

In [21]:
# create two sparse matrices in CSR format
data1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
indices1 = [0, 1, 2, 0, 1, 2, 0, 1, 2]
indptr1 = [0, 3, 6, 9]
matrix1 = csr_matrix((data1, indices1, indptr1), shape=(3, 3))

data2 = [1, 0, 0, 0, 1, 0, 0, 0, 1]
indices2 = [0, 1, 2, 0, 1, 2, 0, 1, 2]
indptr2 = [0, 3, 6, 9]
matrix2 = csr_matrix((data2, indices2, indptr2), shape=(3, 3))

# perform matrix multiplication using CSR format
result = mat_mul_csr(matrix1, matrix2)

# print the resulting sparse matrix
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


implement a function `solve_lin_sys` that takes a matrix `A` in `csr` format and a vector `b` as a numpy array and solves the system `Ax = b`.

In [23]:
def solve_lin_sys(A, b):
    # convert A to csr format if it's not already
    if not isinstance(A, csr_matrix):
        A = csr_matrix(A)
    
    # solve the system Ax = b
    x = spsolve(A, b)
    
    return x

In [24]:
# Example usage
A = csr_matrix([[1, 2, 0], [0, 3, 4], [5, 0, 6]])
b = np.array([1, 2, 3])

x = solve_lin_sys(A, b)

print(x)

[0.31034483 0.34482759 0.24137931]
